url: http://ottumwa1stchurch.github.io
baseurl:
#baseurl: /agency-jekyll-theme/

# Site settings:
title: First Church of the Open Bible 
email: joshmccall221@gmail.com
description: "Welcome to Ottumwa 1st Church of the Open Bible!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Mark Hornback 
  pic: 1
  position: Pastor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #

- name: Bill Hornback 
  pic: 2
  position: Lead Pastor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: facebook
    url:


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
